language: node_js
node_js:
- '4.4'
script: npm install && npm test
before_deploy:
- git config --global user.email "lucian@symposion.co.uk"
- git config --global user.name "Travis-CI"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git checkout master
after_deploy:
- git push --follow-tags origin master
deploy:
- provider: script
  skip_cleanup: true
  script: gulp release
  on:
    repo: symposion/roll20-shaped-scripts
    branch: master
    tags: false
env:
  global:
    secure: GcbJQHdU76uXC+JFQhIH8g1C8yyGiKSEyh1526lAHUXaCoA8TjxjJstYJyrGBUw5nUxyehK397nOMm5ipOqrNXtPz9kCe3Z5u84R7rk1oTFgt4qvpMQGQO2xaBDrXrAcxs52s6No3YQ7xp5BfsyZn9LtHI0QK6z4Aol3feuErqL+K5NA5YV58XIHV3D4ymKqMjY5Xvyw/jUKMZJ8SnYpXllXcPmOieepPESynxQ7+C61ZkTCrISsi/92gnHnhwkVAiJfOi2JsheUsryJsf1tWXIqLTy0YTleKkqn1zCe5Gt2ac4bGRK2jIyreLtXCda0DKAv/Lezkf7pOV/5PEel3c7ekreQapRmCg4/HzoxPxI//H5VIXnXsVaIF7ZAHvBg2BIso9bqaSD2J5M9cQuJDNaPJDlXqJ1YCs4tK41PP8LVR5dN4wOhxJFo4ZumWl/u4Pv4lSi20yiJhrC6hkNcU6jnxkLyuZOhzBqXzPSmGrGVJ5BV1fSca5KvLDmOny8wqpPYegLlbn9j52WL9dDmklq4qLByo2xn1y6mwlY8pOqWyYXTJxyxs2tmRZga1a8lRtLLZowx9XRNsQsF+NyRWnu4FV9RoiN+FmQu4ZwSvBEwVU2RKu0r6alnmhUF74QYjAKdXYm+zWygW8oUhmNS3+JD8OY85+4eGDPaP4wQUOE=
